# Generated by Django 6.0.5 on 2026-05-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status_before', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('permanently_failed', 'Permanently Failed')], max_length=32)),
                ('status_after', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('permanently_failed', 'Permanently Failed')], max_length=32)),
                ('outcome', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notification')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['notification', 'started_at'], name='notificatio_notific_42e2ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'attempt_number'), name='unique_notification_attempt_number')],
            },
        ),
    ]
